[build]
  command = "vite build"
  publish = "dist"
  functions = "netlify/functions"

[blobs]
  # Creates a store for anonymous analytics
  # Netlify will provision this automatically on deploy
  [[blobs.stores]]
    name = "oneiroi-analytics"

[[redirects]]
  from = "/api/flux/*"
  to = "https://api.bfl.ai/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/flux-image"
  to = "/.netlify/functions/flux-image"
  status = 200
  force = true

[[redirects]]
  from = "/api/upload-image"
  to = "/.netlify/functions/upload-image"
  status = 200
  force = true

[[redirects]]
  from = "/api/analytics"
  to = "/.netlify/functions/analytics"
  status = 200
  force = true

[[redirects]]
  from = "/api/analytics-view"
  to = "/.netlify/functions/analytics-view"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


